name: Daily Microsoft Rewards Farm

on:
  schedule:
    - cron: '0 5 * * *'  # Щодня о 5:00 UTC
  workflow_dispatch:

jobs:
  farm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Farmer
        env:
          MS_EMAIL: ${{ secrets.MS_EMAIL }}
          MS_PASSWORD: ${{ secrets.MS_PASSWORD }}
        run: |
          python main.py --email "$MS_EMAIL" --password "$MS_PASSWORD"
